runtime: php55
api_version: 1

handlers:
- url: /
  script: index.html

- url: /css
  static_dir: css

- url: /font
  static_dir: font

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
